---
- hosts: all
  name: create a directory and a file
  tasks:

    - name: Touch a file
      file:
        path: /home/bhawk/ansible/ansible-local/created-file.txt
        state: touch

    - name: Create a directory if it does not exist
      file:
        path: /home/bhawk/ansible/ansible-local/created-directory
        state: directory

    - name: Create a file in the previously created directory
      file:
        path: /home/bhawk/ansible/ansible-local/created-directory/created-file-2.txt
        state: touch
